"""
train_stage5.py - Stage 5: Train ResNet50-UNet using pseudo labels

Input:
- Images from data/images
- Pseudo labels from outputs/pseudo_labels (generated by Stage 4)

Output:
- Stage 5 checkpoints in outputs/stage5_unet
"""

import os
from argparse import Namespace

import config
from tesunet import train as train_unet


def _count_images(folder_path):
    if not os.path.exists(folder_path):
        return 0
    return len([
        f for f in os.listdir(folder_path)
        if f.lower().endswith((".png", ".jpg", ".jpeg"))
    ])


def main():
    print("=" * 60)
    print("STAGE 5: Train ResNet50-UNet with Pseudo Labels")
    print("=" * 60)

    image_dir = config.STAGE5_IMAGE_DIR
    label_dir = config.STAGE5_LABEL_DIR
    output_dir = config.STAGE5_OUTPUT_DIR

    if not os.path.exists(image_dir):
        raise FileNotFoundError(f"Image directory not found: {image_dir}")

    if not os.path.exists(label_dir):
        raise FileNotFoundError(
            f"Pseudo label directory not found: {label_dir}. Run Stage 4 first."
        )

    n_img = _count_images(image_dir)
    n_lbl = _count_images(label_dir)

    if n_img == 0:
        raise RuntimeError(f"No images found in: {image_dir}")

    if n_lbl == 0:
        raise RuntimeError(
            f"No pseudo labels found in: {label_dir}. Run Stage 4 first."
        )

    os.makedirs(output_dir, exist_ok=True)

    print(f"\n[Stage 5] image_dir : {image_dir}")
    print(f"[Stage 5] label_dir : {label_dir}")
    print(f"[Stage 5] output_dir: {output_dir}")
    print(f"[Stage 5] images={n_img}, labels={n_lbl}")

    args = Namespace(
        image_dir=image_dir,
        label_dir=label_dir,
        output_dir=output_dir,
        epochs=config.STAGE5_EPOCHS,
        batch_size=config.STAGE5_BATCH_SIZE,
        lr=config.STAGE5_LR,
        patch_size=config.STAGE5_PATCH_SIZE,
        patches_per_img=config.STAGE5_PATCHES_PER_IMG,
        num_workers=config.NUM_WORKERS,
    )

    train_unet(args)


if __name__ == "__main__":
    main()
